version: '3.8'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=cse5243
    ports:
      - "8888:8888"
    volumes:
      - "./data:/home/jovyan"
